export const Data = {
  names: [
    "Anna",
    "Benjamin",
    "Cartman",
    "Devon",
    "Eisa",
    "Filip",
    "Greg",
    "Haydyn",
    "Irvin",
    "Jacky",
    "Kyle",
    "Lee",
    "Markus",
    "Norrie",
    "Oscar",
    "Randy",
    "Quinn",
    "Stan",
    "Taylor",
    "Umma",
    "Vincent",
    "Wade Wilson",
    "Xin",
    "Zhong",
  ],
  sites: ["yhh", "jvl", "suv", "psp", "der", "usz"],
  countries: ["us", "ro", "jp", "eu", "fr", "md"],
  leagues: ["silver", "gold", "diamond", "legend"],
  messages: [
    "Discovering new ways of making you wait.",
    "Your time is very important to us. Please wait while we ignore you.",
    "Still faster than Windows update.",
    "We are not liable for any broken screens as a result of waiting.",
    "Bored of slow loading spinner?, buy more RAM!",
    "Kindly hold on until I finish a cup of coffee.",
    "We will be back in 1/0 minutes.",
    "Why don't you order a sandwich?",
    "Don't panic, Just count to infinite.",
    "Please wait, Your PC is not a superman!",
    "Counting backwards from Infinity",
    "Don't worry - a few bits tried to escape, but we caught them",
    "The server is powered by a lemon and two electrodes.",
    "We're testing your patience",
    "As if you had any other choice",
    "Follow the white rabbit",
    "It's not you. It's me.",
    "Creating time-loop inversion field",
    "Don't break your screen yet!<br/>I swear it's almost done.",
    "Unicorns are at the end of this road, I promise.",
    "Time flies when you're having fun.",
    "Get some coffee and come back in ten minutes..",
    "Convincing AI not to turn evil..",
    "Java developers never RIP. They just get Garbage Collected.",
    "Cracking military-grade encryption...",
    "BRB, working on my side project",
    "Chuck Norris once urinated in a semi truck's gas tank as a joke....that truck is now known as Optimus Prime.",
    "Chuck Norris doesn't wear a watch. HE decides what time it is.",
    "Mining some bitcoins...",
    "Downloading more RAM..",
    "Never let a computer know you're in a hurry.",
    "Deleting all your hidden porn...",
    "Still faster than Windows update",
    "Please wait while we serve other customers...",
    "Our premium plan is faster",
  ],
};
